### ISSUE TITLE
problem starting plugin

### ISSUE THREAD

**Issue by lukjod** [laur89/deluge-autoremoveplus#11]
[custom-init] No custom files found, skipping...
13:00:55 [ERROR   ][deluge.pluginmanagerbase      :1672] Unable to instantiate plugin 'AutoRemovePlus' from '/config/plugins/AutoRemovePlus-0.6.5.egg'!
13:00:55 [ERROR   ][deluge.pluginmanagerbase      :1672] invalid syntax (core.py, line 648)
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/deluge/pluginmanagerbase.py", line 148, in enable_plugin
    instance = cls(plugin_name.replace('-', '_'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/plugins/AutoRemovePlus-0.6.5.egg/autoremoveplus/__init__.py", line 50, in __init__
    from .core import Core as _plugin_cls
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1322, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1262, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1528, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1502, in _get_spec
  File "<frozen zipimport>", line 111, in find_spec
  File "<frozen importlib._bootstrap>", line 675, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 822, in spec_from_file_location
  File "<frozen zipimport>", line 170, in get_filename
  File "<frozen zipimport>", line 700, in _get_module_code
  File "<frozen zipimport>", line 629, in _compile_source
  File "/config/plugins/AutoRemovePlus-0.6.5.egg/autoremoveplus/core.py", line 648
    await threads.deferToThread(lambda: time.sleep(self.config['post_removal_sleep_sec'])):

**Comment by lukjod** [comment]
ok thx for info, I'm on newest 2.1.1
